import type { Dayjs } from 'dayjs';

export type FormItem = {
    device_type: 'sanitary_napkin' | 'diapers';
    device_model: string;
    device_id: string;
    sample_number: string;
    sample_model: string;
    times_of_add_liquid: number;
    amount_of_liquid: number;
    holding_time: number;
    sampling_at: Dayjs;
    first_absorption_time_samples: {
        first_absorption_time_1: number;
        first_absorption_time_2: number;
        first_absorption_time_3: number;
        first_absorption_time_4: number;
        first_absorption_time_5: number;
    };
    second_absorption_time_samples: {
        second_absorption_time_samples_1: number;
        second_absorption_time_samples_2: number;
        second_absorption_time_samples_3: number;
        second_absorption_time_samples_4: number;
        second_absorption_time_samples_5: number;
    };
    third_absorption_time_samples?: {
        third_absorption_time_samples_1?: number;
        third_absorption_time_samples_2?: number;
        third_absorption_time_samples_3?: number;
        third_absorption_time_samples_4?: number;
        third_absorption_time_samples_5?: number;
    };
    permeation_samples?: {
        permeation_samples_1?: number;
        permeation_samples_2?: number;
        permeation_samples_3?: number;
        permeation_samples_4?: number;
        permeation_samples_5?: number;
    };
    back_seepage_samples: {
        back_seepage_samples_1: number;
        back_seepage_samples_2: number;
        back_seepage_samples_3: number;
        back_seepage_samples_4: number;
        back_seepage_samples_5: number;
    };
};

type AutoGeneratedItem = {
    source_ip: string;
    project_name: string;
    laboratory: string;
    tester: string;
};

export type DiapersItemPayload = {
    data: {
        device_type: 'sanitary_napkin' | 'diapers'; // 设备类型: sanitary_napkin 或 diapers
        device_model: string; // 设备型号
        device_id: string; // 设备 ID
        sample_number: string; // 样品编号
        sample_model: string; // 样品型号
        times_of_add_liquid: number; // 加液次数
        amount_of_liquid: number; // 加液量
        holding_time: number; // 保压时间
        first_absorption_time_samples: number[]; // 一次吸收时间样本
        second_absorption_time_samples: number[]; // 二次吸收时间样本
        third_absorption_time_samples: number[]; // 三次吸收时间样本
        permeation_samples: number[]; // 渗透量
        back_seepage_samples: number[]; // 回渗量
        sampling_at: string; // 打印时间
    };
} & AutoGeneratedItem;

export type SanitaryNapkinItemPayload = {
    data: {
        device_type: 'sanitary_napkin' | 'diapers';
        device_model: string;
        device_id: string;
        sample_number: string;
        sample_model: string;
        times_of_add_liquid: number;
        amount_of_liquid: number;
        holding_time: number;
        first_absorption_time_samples: number[];
        second_absorption_time_samples: number[];
        back_seepage_samples: number[];
        sampling_at: string;
    };
} & AutoGeneratedItem;
