import type { Dayjs } from 'dayjs';

export type FormItem = {
    device_type: 'sanitary_napkin' | 'diaper';
    device_model: string;
    device_id: string;
    sample_number: string;
    sample_model: string;
    times_of_add_liquid: number;
    amount_of_liquid: number;
    holding_time: number;
    sampling_at: Dayjs;
    first_absorption_time_samples: {
        first_absorption_time_1: number;
        first_absorption_time_2: number;
        first_absorption_time_3: number;
        first_absorption_time_4: number;
        first_absorption_time_5: number;
    };
    second_absorption_time_samples: {
        second_absorption_time_samples_1: number;
        second_absorption_time_samples_2: number;
        second_absorption_time_samples_3: number;
        second_absorption_time_samples_4: number;
        second_absorption_time_samples_5: number;
    };
    third_absorption_time_samples?: {
        third_absorption_time_samples_1?: number;
        third_absorption_time_samples_2?: number;
        third_absorption_time_samples_3?: number;
        third_absorption_time_samples_4?: number;
        third_absorption_time_samples_5?: number;
    };
    permeation_samples?: {
        permeation_samples_1?: number;
        permeation_samples_2?: number;
        permeation_samples_3?: number;
        permeation_samples_4?: number;
        permeation_samples_5?: number;
    };
    back_seepage_samples: {
        back_seepage_samples_1: number;
        back_seepage_samples_2: number;
        back_seepage_samples_3: number;
        back_seepage_samples_4: number;
        back_seepage_samples_5: number;
    };
};

type AutoGeneratedItem = {
    source_ip: string;
    project_name: string;
    laboratory: string;
    tester: string;
};
export type DiapersItemPayload = {
    data: {
        device_type: 'sanitary_napkin' | 'diaper'; // 设备类型: sanitary_napkin 或 diaper
        device_model: string; // 设备型号
        device_id: string; // 设备 ID
        sample_number: string; // 样品编号
        sample_model: string; // 样品型号
        times_of_add_liquid: number; // 加液次数
        amount_of_liquid: number; // 加液量
        holding_time: number; // 保压时间
        first_absorption_time_samples: number[]; // 一次吸收时间样本
        second_absorption_time_samples: number[]; // 二次吸收时间样本
        third_absorption_time_samples: number[]; // 三次吸收时间样本
        permeation_samples: number[]; // 渗透量
        back_seepage_samples: number[]; // 回渗量
        sampling_at: string; // 打印时间
    };
} & AutoGeneratedItem;
export type SanitaryNapkinItemPayload = {
    data: {
        device_type: 'sanitary_napkin' | 'diaper';
        device_model: string;
        device_id: string;
        sample_number: string;
        sample_model: string;
        times_of_add_liquid: number;
        amount_of_liquid: number;
        holding_time: number;
        first_absorption_time_samples: number[];
        second_absorption_time_samples: number[];
        back_seepage_samples: number[];
        sampling_at: string;
    };
} & AutoGeneratedItem;

export const DIAPER_DEVICE_MODEL_OPTIONS = [
    { label: 'T025A', value: 'T025A' },
    { label: 'T025B', value: 'T025B' },
];
export const SANITARY_NAPKIN_DEVICE_MODEL_OPTIONS = [
    { label: 'T017B', value: 'T017B' },
    { label: 'T017C', value: 'T017C' },
];
export const DIAPER_SAMPLE_MODEL_OPTIONS = [
    { label: 'NB-尿裤', value: '0' },
    { label: 'S-尿裤', value: '1' },
    { label: 'M-尿裤', value: '2' },
    { label: 'L-尿裤', value: '3' },
    { label: 'XL-尿裤', value: '4' },
    { label: 'XXL-尿裤', value: '5' },
    { label: '成人中度-尿裤', value: '6' },
    { label: '成人重度-尿裤', value: '7' },
    { label: 'NB-尿片', value: '8' },
    { label: 'S-尿片', value: '9' },
    { label: 'M-尿片', value: '10' },
    { label: 'L-尿片', value: '11' },
    { label: 'XL-尿片', value: '12' },
    { label: 'XXL-尿片', value: '13' },
    { label: '成人中度-尿片', value: '14' },
    { label: '成人重度-尿片', value: '15' },
];
export const SANITARY_SAMPLE_MODEL_OPTIONS = [
    { label: '卫生巾', value: 0 },
    { label: '卫生裤', value: 1 },
];
export const DIAPER_SAMPLE_MODEL_LIQUID_AMOUNT_MAP: Record<string, number> = {
    '0': 40,
    '1': 40,
    '2': 60,
    '3': 80,
    '4': 80,
    '5': 80,
    '6': 100,
    '7': 150,
    '8': 30,
    '9': 30,
    '10': 40,
    '11': 50,
    '12': 50,
    '13': 50,
    '14': 70,
    '15': 100,
};
