/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentInfoCollectionIndexRouteImport } from './routes/equipment-info-collection/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentInfoCollectionIndexRoute =
  EquipmentInfoCollectionIndexRouteImport.update({
    id: '/equipment-info-collection/',
    path: '/equipment-info-collection/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment-info-collection/': typeof EquipmentInfoCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipment-info-collection': typeof EquipmentInfoCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment-info-collection/': typeof EquipmentInfoCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipment-info-collection/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipment-info-collection'
  id: '__root__' | '/' | '/equipment-info-collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentInfoCollectionIndexRoute: typeof EquipmentInfoCollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment-info-collection/': {
      id: '/equipment-info-collection/'
      path: '/equipment-info-collection'
      fullPath: '/equipment-info-collection/'
      preLoaderRoute: typeof EquipmentInfoCollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentInfoCollectionIndexRoute: EquipmentInfoCollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
